In [1]:
import numpy as np

# Creating a multidimensional array.

In [2]:
list_of_lists = np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
list_of_lists.shape                   # Use the shape method to find the dimensions of the array. (row, columns)

(3, 3)

In [4]:
np.arange(0,10)           # Start from zero, generate 10 numbers. NB: the last digit will not appear.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
for i in range(0,10):
    print(i)
                                  # Its using for statement the give output in this form and numpy give output in array forms.

0
1
2
3
4
5
6
7
8
9


In [6]:
np.arange(10)            # Numpy will be intelligent to generate 10 numbers excluding the last digit.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)        # Generating numbers from 0 to 10 in an interval of 2

array([0, 2, 4, 6, 8])

In [11]:
for i in range(0,10,2):
    print(i)                           # Same as arange like that with 2 interval

0
2
4
6
8


In [12]:
for i in range(0,10,3):                   # With 3 interval by for statement
    print(i)

0
3
6
9


In [13]:
np.arange(0,10,3)                            # Generating numbers from 0 to 10 in an interval 3 by using numpy

array([0, 3, 6, 9])

In [14]:
zero = np.zeros(100)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
zero_1 = np.zeros(50)
zero_1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones((3, 3))                    # In this you mention shape of arrays.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
a = np.eye(10)
a                                               # Identity matrix (10, 10).

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
b = np.eye(6)
b

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
mn = np.arange(0,50,2)              # Start from 0 count up by 2, stop before 20.
mn

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [24]:
len(mn)

25

In [20]:
mn = np.arange(0,50)
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [21]:
len(mn)

50

In [26]:
mn.reshape(5,5)                     # shape of array is multiple no. then that is show output nothing it's show error.

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [27]:
mn.reshape(5,3)                             # like this ( Because 5*3=15 its not 25, "25 is the length of array")

ValueError: cannot reshape array of size 25 into shape (5,3)

In [39]:
mn.reshape(1,25)

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38, 40, 42, 44, 46, 48]])

In [40]:
mn.reshape(25,1)                              # 0nly multiple no. with 25

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28],
       [30],
       [32],
       [34],
       [36],
       [38],
       [40],
       [42],
       [44],
       [46],
       [48]])

In [35]:
mn

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [32]:
o = np.linspace(0, 7, 10)                 # Return 10 evenly spaced values from0 to 7, NB: It usaully gives output in decimals unlike the arange function 
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [30]:
len(o)

10

In [37]:
c = np.linspace(0,8,20)
c

array([0.        , 0.42105263, 0.84210526, 1.26315789, 1.68421053,
       2.10526316, 2.52631579, 2.94736842, 3.36842105, 3.78947368,
       4.21052632, 4.63157895, 5.05263158, 5.47368421, 5.89473684,
       6.31578947, 6.73684211, 7.15789474, 7.57894737, 8.        ])

In [38]:
d = np.linspace(0,7,100)
d

array([0.        , 0.07070707, 0.14141414, 0.21212121, 0.28282828,
       0.35353535, 0.42424242, 0.49494949, 0.56565657, 0.63636364,
       0.70707071, 0.77777778, 0.84848485, 0.91919192, 0.98989899,
       1.06060606, 1.13131313, 1.2020202 , 1.27272727, 1.34343434,
       1.41414141, 1.48484848, 1.55555556, 1.62626263, 1.6969697 ,
       1.76767677, 1.83838384, 1.90909091, 1.97979798, 2.05050505,
       2.12121212, 2.19191919, 2.26262626, 2.33333333, 2.4040404 ,
       2.47474747, 2.54545455, 2.61616162, 2.68686869, 2.75757576,
       2.82828283, 2.8989899 , 2.96969697, 3.04040404, 3.11111111,
       3.18181818, 3.25252525, 3.32323232, 3.39393939, 3.46464646,
       3.53535354, 3.60606061, 3.67676768, 3.74747475, 3.81818182,
       3.88888889, 3.95959596, 4.03030303, 4.1010101 , 4.17171717,
       4.24242424, 4.31313131, 4.38383838, 4.45454545, 4.52525253,
       4.5959596 , 4.66666667, 4.73737374, 4.80808081, 4.87878788,
       4.94949495, 5.02020202, 5.09090909, 5.16161616, 5.23232

In [33]:
o.resize(5, 2)
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [34]:
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [36]:
mn

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

**Assignment:** What is the difference between **"resize"** and **"reshape"**?

**Solution:**<br> reshape() and numpy. resize() methods are used to change the size of a NumPy array. The difference between them is that the reshape() does not changes the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array.

In [41]:
# Above "o" and "mn" shows the examples of reshape and resize.

# Generate some random values

In [42]:
np.random.rand(3,2)              # Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1]

array([[0.68021887, 0.63780143],
       [0.64268983, 0.50815692],
       [0.82197087, 0.84303419]])

In [48]:
e = np.random.rand(3, 3)         # Return a sample (or sample) from the "standard normal" distribution.
e

array([[0.98431777, 0.68508993, 0.55092567],
       [0.22265701, 0.43059575, 0.001019  ],
       [0.23380379, 0.47446905, 0.08906759]])

In [50]:
# Generating 10 numbers between 4 and 15
mn = np.random.randint(4,15,10)             # Return random integers from low (inclusive) to high (exclusive).

In [51]:
mn                                   # They give each an every time random no. in output.

array([ 8,  9, 10,  6, 14,  8,  7,  5,  9, 12])

In [54]:
len(mn)

10

In [52]:
mn.reshape(5, 2)

array([[ 8,  9],
       [10,  6],
       [14,  8],
       [ 7,  5],
       [ 9, 12]])

In [53]:
mn.reshape(5,3)                        # Because their is (5, 3) no multiple of 10.

ValueError: cannot reshape array of size 10 into shape (5,3)

In [64]:
mn = np.random.randint(2,20,15)                        # In this the output elements is 15 numbers in between 2 to 5

In [65]:
mn

array([15,  9,  2,  9,  8, 17, 11, 14, 19, 10, 18, 19, 13, 18,  6])

In [66]:
len(mn)

15

In [67]:
mn.reshape(5,3)

array([[15,  9,  2],
       [ 9,  8, 17],
       [11, 14, 19],
       [10, 18, 19],
       [13, 18,  6]])

In [68]:
mn                              # After change the shape by reshape comand they give orignal array.

array([15,  9,  2,  9,  8, 17, 11, 14, 19, 10, 18, 19, 13, 18,  6])

In [69]:
mn.resize(5,3)
mn

array([[15,  9,  2],
       [ 9,  8, 17],
       [11, 14, 19],
       [10, 18, 19],
       [13, 18,  6]])

In [70]:
mn                           # But the shape change by the resize comand they change the shape permantly.

array([[15,  9,  2],
       [ 9,  8, 17],
       [11, 14, 19],
       [10, 18, 19],
       [13, 18,  6]])

In [58]:
tt = np.random.randint(0, 10, (4, 3))                   # In this the no. between 0 to 10 the shape of (4,3)
tt

array([[2, 4, 5],
       [9, 6, 1],
       [3, 4, 4],
       [7, 7, 0]])

In [71]:
pp = np.random.randint(0, 10, (15, 20))
pp

array([[7, 5, 2, 9, 7, 4, 7, 2, 1, 6, 9, 7, 5, 6, 8, 8, 8, 4, 3, 5],
       [0, 6, 9, 2, 5, 2, 0, 5, 3, 5, 1, 5, 1, 4, 0, 9, 2, 7, 1, 9],
       [3, 1, 7, 8, 7, 2, 4, 1, 0, 4, 7, 3, 5, 9, 0, 8, 2, 4, 1, 4],
       [2, 9, 5, 1, 3, 8, 1, 4, 5, 6, 6, 4, 7, 8, 2, 8, 4, 0, 9, 0],
       [0, 1, 9, 1, 6, 9, 8, 7, 1, 0, 5, 2, 6, 4, 5, 5, 1, 9, 7, 5],
       [8, 6, 9, 4, 2, 9, 6, 7, 0, 4, 4, 1, 9, 9, 7, 1, 0, 6, 0, 3],
       [2, 5, 5, 5, 1, 3, 8, 9, 3, 7, 3, 4, 2, 7, 3, 2, 6, 1, 4, 3],
       [2, 5, 7, 0, 4, 0, 3, 1, 0, 5, 7, 2, 3, 5, 3, 4, 3, 8, 0, 9],
       [5, 2, 8, 8, 9, 1, 7, 3, 1, 5, 2, 7, 9, 2, 1, 1, 0, 2, 7, 3],
       [6, 4, 8, 3, 1, 2, 5, 7, 5, 7, 9, 8, 8, 0, 3, 7, 0, 1, 7, 7],
       [1, 6, 6, 2, 0, 0, 6, 0, 6, 1, 8, 7, 7, 4, 9, 7, 3, 8, 8, 0],
       [5, 4, 6, 9, 0, 4, 0, 8, 4, 6, 3, 5, 2, 2, 4, 3, 5, 0, 3, 5],
       [0, 8, 7, 6, 4, 7, 6, 7, 8, 5, 2, 3, 5, 7, 9, 8, 9, 3, 9, 9],
       [3, 2, 1, 6, 9, 7, 4, 1, 2, 9, 9, 1, 7, 1, 0, 7, 4, 9, 6, 7],
       [9, 1, 2, 4, 9, 8, 5, 3, 1,