# Indexing and Slicing

In [2]:
import numpy as np

In [6]:
mn = np.random.randint(4, 15, 10)
mn

array([ 6, 10, 12, 10,  9,  4,  8,  5,  9,  5])

In [7]:
mn[1]                                # Indexing start from front 0,1,2....so on.

10

In [8]:
mn[-1]                               # The -ve indexing start from end -1,-2,-3,.....so on.

5

In [9]:
mn[5]

4

In [10]:
mn[-5]

4

In [11]:
mn[3:7]                  # Selecting items within range.  The range elements is : [3,4,5,6]

array([10,  9,  4,  8])

In [12]:
mn[3:]                          # The range is :[3 to last element]

array([10,  9,  4,  8,  5,  9,  5])

In [13]:
mn[-1]     

5

In [14]:
mn[5:-2]                          # The range is : [5,6,7] because -2 is nothing but 8.

array([4, 8, 5])

In [15]:
mn.resize(2,5)

In [16]:
mn

array([[ 6, 10, 12, 10,  9],
       [ 4,  8,  5,  9,  5]])

In [19]:
mm=np.arange(36)
mm

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [20]:
mm.resize(6,6)

In [21]:
mm

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [24]:
mm[2,3]                    # the element of 2nd row 3rd column

15

In [25]:
mm[4, 2:5]           # Use : to select a range of rows or columns,
                      # 4th row the element range is [2,3,4]

array([26, 27, 28])

In [27]:
mm[2:]                      # From 2nd row to last.

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [33]:
mm[3::,3:]                   # start from 3rd row 3rd column up to last.

array([[21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [29]:
mm[3::]                      # start from 3dr rows up to last

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [34]:
mm[3::,3]                 # 3rd row and the element of 3rd column element is[3,4,5]

array([21, 27, 33])

### Conditional indexing

In [35]:
mm[mm > 25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [38]:
mm[mm > 25]=25                # Casting all the values that are greater than 25 to 25

In [37]:
mm

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

In [39]:
mm[1:,4]                     # 1st row and 4th column elements [1,2,3,4,5]

array([10, 16, 22, 25, 25])

In [40]:
mm[1:,4]

array([10, 16, 22, 25, 25])

In [41]:
mm[mm<25]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
mm[mm<25]=5

In [43]:
mm

array([[ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5,  5],
       [ 5, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

### Creating Copy

In [44]:
mn1 = mm[3:,3:]
mn1

array([[ 5,  5,  5],
       [25, 25, 25],
       [25, 25, 25]])

In [45]:
mn_copy=mm.copy()
mn_copy

array([[ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5,  5],
       [ 5, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

In [47]:
mn_copy[mn_copy>5]=5                # Broadcast all the numbers greater than 5 as 5
mn_copy

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [48]:
mm

array([[ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5,  5,  5],
       [ 5, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])